FROM --platform=linux/amd64 public.ecr.aws/lambda/python:3.9
RUN yum install -y zip
WORKDIR /lambda

RUN pip install build

ADD . /src/
RUN cd /src/ && \
        python -m build && \
        pip install --target /lambda dist/*.whl

RUN find /lambda -type d -print0 | xargs -0 chmod ugo+rx && \
    find /lambda -type f -print0 | xargs -0 chmod ugo+r

RUN python -m compileall -q /lambda

ARG ZIPFILE=lambda.zip
RUN zip --quiet -9r /${ZIPFILE}  .

FROM scratch
ARG ZIPFILE
COPY --from=0 /${ZIPFILE} /